# Streamlined Supabase Edge Functions Configuration
# Only essential functions for WebRTC-based softphone system

# Phone Number Management
[functions.search-available-numbers]
enabled = true
verify_jwt = true
import_map = "./functions/search-available-numbers/deno.json"
entrypoint = "./functions/search-available-numbers/index.ts"

[functions.purchase-phone-number]
enabled = true
verify_jwt = true
import_map = "./functions/purchase-phone-number/deno.json"
entrypoint = "./functions/purchase-phone-number/index.ts"

[functions.list-signalwire-phone-numbers]
enabled = true
verify_jwt = true
import_map = "./functions/list-signalwire-phone-numbers/deno.json"
entrypoint = "./functions/list-signalwire-phone-numbers/index.ts"

# WebRTC Voice Calling
[functions.generate-signalwire-voice-token]
enabled = true
verify_jwt = true
import_map = "./functions/generate-signalwire-voice-token/deno.json"
entrypoint = "./functions/generate-signalwire-voice-token/index.ts"

[functions.start-outbound-call]
enabled = true
verify_jwt = true
import_map = "./functions/start-outbound-call/deno.json"
entrypoint = "./functions/start-outbound-call/index.ts"

[functions.handle-call-control]
enabled = true
verify_jwt = true
import_map = "./functions/handle-call-control/deno.json"
entrypoint = "./functions/handle-call-control/index.ts"

[functions.send-dtmf]
enabled = true
verify_jwt = true
import_map = "./functions/send-dtmf/deno.json"
entrypoint = "./functions/send-dtmf/index.ts"

# SMS Messaging
[functions.send-sms]
enabled = true
verify_jwt = true
import_map = "./functions/send-sms/deno.json"
entrypoint = "./functions/send-sms/index.ts"

[functions.handle-incoming-sms]
enabled = true
verify_jwt = true
import_map = "./functions/handle-incoming-sms/deno.json"
entrypoint = "./functions/handle-incoming-sms/index.ts"

# Video Meetings
[functions.create-video-room]
enabled = true
verify_jwt = true
import_map = "./functions/create-video-room/deno.json"
entrypoint = "./functions/create-video-room/index.ts"

[functions.generate-signalwire-token]
enabled = true
verify_jwt = true
import_map = "./functions/generate-signalwire-token/deno.json"
entrypoint = "./functions/generate-signalwire-token/index.ts"

# Location Tracking (for technician tracking)
[functions.start-technician-tracking]
enabled = true
verify_jwt = true
import_map = "./functions/start-technician-tracking/deno.json"
entrypoint = "./functions/start-technician-tracking/index.ts"

[functions.update-technician-location]
enabled = true
verify_jwt = true
import_map = "./functions/update-technician-location/deno.json"
entrypoint = "./functions/update-technician-location/index.ts"

[functions.get-technician-location]
enabled = true
verify_jwt = true
import_map = "./functions/get-technician-location/deno.json"
entrypoint = "./functions/get-technician-location/index.ts"

# Subproject Management (if using subproject system)
[functions.create-signalwire-subproject]
enabled = true
verify_jwt = true
import_map = "./functions/create-signalwire-subproject/deno.json"
entrypoint = "./functions/create-signalwire-subproject/index.ts"

[functions.retry-subproject-creation]
enabled = true
verify_jwt = true
import_map = "./functions/retry-subproject-creation/deno.json"
entrypoint = "./functions/retry-subproject-creation/index.ts"

[functions.complete-full-onboarding]
enabled = true
verify_jwt = true
import_map = "./functions/complete-full-onboarding/deno.json"
entrypoint = "./functions/complete-full-onboarding/index.ts"

# REMOVED FUNCTIONS (for reference):
# - create-sip-trunk (not needed for WebRTC)
# - list-sip-endpoints (not needed for WebRTC)
# - provision-signalwire-endpoint (not needed for WebRTC)
# - create-signalwire-sip-endpoints (not needed for WebRTC)
# - create-sip-endpoint (not needed for WebRTC)
# - create-signalwire-video-room (redundant with create-video-room)
# - generate-webrtc-token (redundant with generate-signalwire-voice-token)
# - list-webrtc-phone-numbers (can be handled by frontend logic)
# - simple-bridge-call (can be handled by start-outbound-call)
# - update-signalwire-phone-number (admin task, not needed as function)
# - release-signalwire-phone-number (admin task, not needed as function)
# - test-signalwire-sip-to-webrtc (testing function, not production)
# - handle-call-control (if not used)
# - get-technician-location (if not used)
# - create-sip-configuration (if not needed for WebRTC setup)
# - list-signalwire-sip-endpoints (if not needed for WebRTC)
# - test-jwt-generation (testing function)
[functions.generate-estimate]
enabled = true
verify_jwt = true
import_map = "./functions/generate-estimate/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-estimate/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-estimate/*.html" ]
